### ISSUE TITLE
Usability tweaks

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--visual-exploration-gaussian-processes#29]
Jochen & Co-authors, this is looking _great_! 

Here's a small list of suggestions after which I'd suggest you could transfer the repository to the Github org `distillpub` where I'll ensure technical compatibility. 

_(E.g. We'll need to link against the most current version of the Distill template served by distill.pub. At the moment you may see math type out of place—this is a regression in newer versions of Chrome because the article is currently linking against an outdated build of the Distill template. In order to fix such bugs in the future without your input, we require linking against the hosted version of template. We also have our own webcomponents loader already built into the Distill template, and we need to create the meta tags programmatically to allow DOI uploading and other indexing. We'll also need to remove your Google Analytics snippet unfortunately. EDIT: I'll check about that with the other editors, actually. We haven't historically allowed this, but I wonder whether we have consciously thought about this. No guarantees, but I'll inquire. :-))_

### Make the draggable area of handles at least 44px big
At the moment it can be extremely hard to hit the handles on the Gaussian distribution diagrams. I'd suggest to do this with an invisible circle of radius 44px that intercepts mouse events the same way the current handles work. Please also set `cursor: grab;` on those elements to shwo they can be moved.

### Maybe introduce Gaussian distribution parameters one-by-one
You already have a nice interactive diagram for a full Gaussian distribution. You could consider having the diagram be visible every time you introduce a parameter, with only that parameter changeable. So e.g. when you talk about "The diagonal of Σ consists of the variance \sigma_i^2σ of the ii -th random variable." it would be great to have the diagram with only the parameters on the diagonal adjustable. 

This is just a suggestion to make the very introduction of Gaussian distributions more approachable. In our experience it is often valuable to focus on making the earliest sections of an explanation as accessible to readers as possible. 

### Add links to set state of figure #Posterior to its figcaption
In the (beautifully done!) figure #Posterior's figcaption you describe different states of the figure. It can help discoverability a lot to supply links on the relevant parts of the figcaption that on click call JS that sets the figure to the described state. [Take a look](https://distill.pub/2018/building-blocks/#SemanticDict) (under) for an example of this behavior.

![image](https://user-images.githubusercontent.com/1167977/52754058-079c2780-2fae-11e9-9182-a6620abf4870.png)
Clicking on the underlined text sets the position of the square in the above diagram to the described feature.

I'd recommend this approach for each of the italicized scenarios:
> _Without any activated training data_, this figure shows the prior distribution of a Gaussian process with a RBF kernel. When _hovering over the covariance matrix_, the opacity of the gradient shows the influence of a function value on its neighbours. The distribution changes when we _observe training data_. Individual points can be activated by clicking on them. The Gaussian process is then constrained to make functions, that intersect these data points, more probable. The best explanation of the training data is given by the updated mean function.

(Please also remove at least the left margin of this figure so it aligns with the body text.)

**Comment by theosanderson** [comment]
Amazing article.

At the moment the invisible handles work but the visible handles don't - so if you are too accurate with the mouse you are unable to drag (on my version of Chrome). With the instructions, and the hover animation, this is quite non-intuitive and threw me for a while. I don't know how hard it would be to solve.

**Comment by ludwigschubert** [comment]
@theosanderson can reproduce, thanks for taking the time to write an issue.

@RKehlbeck Could it be the invisible overlay needs to be on top of the visible handle? I just tried reordering them in dev tools (move both `circle.handleInvisible` tags to be the last SVG elements renders them on top) and then drag events work always.

**Comment by ludwigschubert** [comment]
@RKehlbeck @theosanderson fixed in #48 — I just reordered nodes in your SVG drawing code. It's deploying atm. :-)
