### ISSUE TITLE
Minor typo in text

### ISSUE THREAD

**Issue by jmloyola** [distillpub/post--visual-exploration-gaussian-processes#38]
There is a minor typo in the text:
> We will first explore the mathematical foundation that Gaussian __procsses__ are built on — we invite you to follow along using the interactive figures and hands-on examples. 

It should be:
>We will first explore the mathematical foundation that Gaussian __processes__ are built on — we invite you to follow along using the interactive figures and hands-on examples.

**Comment by grtlr** [comment]
Thanks! Ref. PR #39
