### ISSUE TITLE
I can't grab the handles in draggable figures directly

### ISSUE THREAD

**Issue by girving** [distillpub/post--visual-exploration-gaussian-processes#43]
In this figure, in order to drag the vertical line from side to side, I have to start clicking *off* the vertical line.  This is unintuitive: I'd expect to be able to click on the object to be dragged and drag it.

<img width="718" alt="Screen Shot 2019-04-03 at 11 49 52 AM" src="https://user-images.githubusercontent.com/70511/55504856-9caeba80-5606-11e9-9fcd-c5ae5a718e21.png">

**Comment by ludwigschubert** [comment]
Jupp, they seem to be in the wrong z order. Tracking in #29, but leaving this open for now as a reminder that all diagrams with handles have this issue. :-)

**Comment by ludwigschubert** [comment]
Fixed in #48 via 93e6fc :-)

**Comment by girving** [comment]
Thank you!
