### ISSUE TITLE
Marginalization and Conditioning figure caption - minor typo

### ISSUE THREAD

**Issue by tmatha** [distillpub/post--visual-exploration-gaussian-processes#49]
Thank you for a nicely illustrated article. A minor typo or what I think is a minor typo -
"On the left you can see the result of marginalizing this distribution for Y, akin to integrating along the Y axis."
In the above sentence, "akin to integrating along the Y axis" should be changed to "akin to integrating along the X axis".

**Comment by grtlr** [comment]
You are right—thank you very much!
