### ISSUE TITLE
Confusing wording in section on posterior distribution

### ISSUE THREAD

**Issue by atharva-kelkar** [distillpub/post--visual-exploration-gaussian-processes#60]
Hi,

You state that "In contrast to the prior distribution, we set the mean to \mu=0.". 

Would this be clearer if it stated "In contrast to the prior distribution where we set the mean to \mu=0,  the resulting distribution will most likely have a non-zero mean \mu’ \neq 0"?

Or is there something I'm missing and not understanding correctly?

**Comment by grtlr** [comment]
You are right, this seems weird. I will take a look at it later today. Thank you for filing this!
